---
- name: Create system groups
  group:
    name: "{{ item.1 }}"
    state: present
    system: yes
  loop: "{{ q('subelements', users, 'system_groups', {'skip_missing': True}) | unique }}"

- name: Add the users to the groups
  user:
    name: "{{ item.0.name }}"
    state: present
    groups: "{{ item.1 }}"
    append: yes
  loop: "{{ q('subelements', users, 'system_groups', {'skip_missing': True}) }}"

- name: Create daemon users
  user:
    name: "{{ item }}"
    state: present
    create_home: no
    password: "!"
    shell: "/usr/sbin/nologin"
    system: no
  loop: "{{ daemon_users if daemon_users is iterable else [] }}"
  register: daemon_user_list

- name: Print daemon users
  debug:
    var: daemon_user_list

- name: Set conntrack max size
  sysctl:
    name: "net.netfilter.nf_conntrack_max"
    value: 16777216
    state: present
    sysctl_set: yes
    reload: yes

- name: Set max socket size
  sysctl:
    name: "{{ item }}"
    value: 16777216
    state: present
    sysctl_set: yes
    reload: yes
  loop:
    - "net.core.rmem_max"
    - "net.core.wmem_max"

- name: Enable fair queue discipline
  sysctl:
    name: "net.core.default_qdisc"
    value: "fq"
    state: present
    sysctl_set: yes
    reload: yes

- name: Enable BBR TCP congestion control
  sysctl:
    name: "net.ipv4.tcp_congestion_control"
    value: "bbr"
    state: present
    sysctl_set: yes
    reload: yes
...
